//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Index.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_NotasEstudiante
    {
        public int id_estudiante { get; set; }
        public string Nombre { get; set; }
        public decimal Laboratorio1 { get; set; }
        public decimal Parcial1 { get; set; }
        public decimal Laboratorio2 { get; set; }
        public decimal Parcial2 { get; set; }
        public decimal Laboratorio3 { get; set; }
        public decimal Parcial3 { get; set; }
        public decimal NotaTotal { get; set; }
    }
}
